// ── Bagrut-style question bank: פונקציות טריגונומטריות + פונקציות רציונליות ──
// Original questions written in the style of Israeli bagrut exams.
// Inserted idempotently by seedBagrut:seedBagrutQuestions (dedup by stem).

import type { SimpleQuestionSeed } from "./seedBagrutData1";

export const TRIG_QUESTIONS: SimpleQuestionSeed[] = [
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 1,
    stem: "מהו ערכו של $\\sin 30°$?",
    choices: ["$\\frac{1}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{2}}{2}$", "1"],
    correctIndex: 0,
    solutionSteps: [
      "זהו אחד מהערכים המיוחדים שיש לזכור",
      "$\\sin 30° = \\frac{1}{2}$",
    ],
    hint: "זכור את הערכים המיוחדים של הזוויות 30°, 45°, 60°.",
    explanation: "$\\sin 30° = \\frac{1}{2}$ — ערך מיוחד שכדאי לזכור בעל פה.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 1,
    stem: "מהו ערכו של $\\tan 45°$?",
    choices: ["1", "$\\frac{1}{2}$", "$\\sqrt{3}$", "$\\frac{\\sqrt{2}}{2}$"],
    correctIndex: 0,
    solutionSteps: [
      "$\\tan 45° = \\frac{\\sin 45°}{\\cos 45°}$",
      "$\\sin 45° = \\cos 45° = \\frac{\\sqrt{2}}{2}$",
      "$\\tan 45° = 1$",
    ],
    hint: "בזווית 45° הסינוס והקוסינוס שווים.",
    explanation: "מכיוון ש-$\\sin 45° = \\cos 45°$, מתקבל $\\tan 45° = 1$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 1,
    stem: "מהי האמפליטודה של הפונקציה $f(x) = 5\\sin(2x) - 3$?",
    choices: ["5", "2", "3", "8"],
    correctIndex: 0,
    solutionSteps: [
      "בפונקציה מהצורה $a\\sin(bx) + c$ האמפליטודה היא $|a|$",
      "כאן $a = 5$, ולכן האמפליטודה היא 5",
    ],
    hint: "האמפליטודה היא המקדם של הסינוס (בערך מוחלט).",
    explanation: "האמפליטודה נקבעת על ידי המקדם של הסינוס: 5.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 2,
    stem: "מהי התקופה של הפונקציה $f(x) = \\sin(2x)$?",
    choices: ["$\\pi$", "$2\\pi$", "$\\frac{\\pi}{2}$", "$4\\pi$"],
    correctIndex: 0,
    solutionSteps: [
      "התקופה של $\\sin(bx)$ היא $\\frac{2\\pi}{b}$",
      "$T = \\frac{2\\pi}{2} = \\pi$",
    ],
    hint: "התקופה של $\\sin(bx)$ היא $\\frac{2\\pi}{b}$.",
    explanation: "$T = \\frac{2\\pi}{2} = \\pi$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 2,
    stem: "מהי התקופה של הפונקציה $f(x) = \\cos(3x)$?",
    choices: ["$\\frac{2\\pi}{3}$", "$\\frac{\\pi}{3}$", "$3\\pi$", "$2\\pi$"],
    correctIndex: 0,
    solutionSteps: [
      "התקופה של $\\cos(bx)$ היא $\\frac{2\\pi}{b}$",
      "$T = \\frac{2\\pi}{3}$",
    ],
    hint: "התקופה של $\\cos(bx)$ היא $\\frac{2\\pi}{b}$.",
    explanation: "$T = \\frac{2\\pi}{3}$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 2,
    stem: "מהו הערך המקסימלי של הפונקציה $f(x) = 3\\sin x + 1$?",
    choices: ["4", "3", "1", "2"],
    correctIndex: 0,
    solutionSteps: [
      "הערך המקסימלי של $\\sin x$ הוא 1",
      "$f_{max} = 3 \\cdot 1 + 1 = 4$",
    ],
    hint: "מהו הערך הגדול ביותר ש-$\\sin x$ יכול לקבל?",
    explanation: "כאשר $\\sin x = 1$ מתקבל $f = 4$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 2,
    stem: "מהו הערך המינימלי של הפונקציה $f(x) = 2\\cos x - 1$?",
    choices: ["-3", "-1", "-2", "1"],
    correctIndex: 0,
    solutionSteps: [
      "הערך המינימלי של $\\cos x$ הוא $-1$",
      "$f_{min} = 2 \\cdot (-1) - 1 = -3$",
    ],
    hint: "מהו הערך הקטן ביותר ש-$\\cos x$ יכול לקבל?",
    explanation: "כאשר $\\cos x = -1$ מתקבל $f = -3$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 2,
    stem: "נתון ש-$x$ זווית חדה ו-$\\sin x = \\frac{3}{5}$. מהו $\\cos x$?",
    choices: ["$\\frac{4}{5}$", "$\\frac{3}{4}$", "$\\frac{2}{5}$", "$\\frac{5}{4}$"],
    correctIndex: 0,
    solutionSteps: [
      "הזהות: $\\sin^2 x + \\cos^2 x = 1$",
      "$\\cos^2 x = 1 - \\frac{9}{25} = \\frac{16}{25}$",
      "$x$ חדה, ולכן $\\cos x = \\frac{4}{5}$",
    ],
    hint: "השתמש בזהות $\\sin^2 x + \\cos^2 x = 1$.",
    explanation: "$\\cos x = \\sqrt{1 - \\frac{9}{25}} = \\frac{4}{5}$ (חיובי כי הזווית חדה).",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 2,
    stem: "נתון ש-$x$ זווית חדה, $\\sin x = \\frac{3}{5}$ ו-$\\cos x = \\frac{4}{5}$. מהו $\\tan x$?",
    choices: ["$\\frac{3}{4}$", "$\\frac{4}{3}$", "$\\frac{3}{5}$", "$\\frac{12}{25}$"],
    correctIndex: 0,
    solutionSteps: [
      "$\\tan x = \\frac{\\sin x}{\\cos x}$",
      "$\\tan x = \\frac{3/5}{4/5} = \\frac{3}{4}$",
    ],
    hint: "טנגנס הוא מנת הסינוס בקוסינוס.",
    explanation: "$\\tan x = \\frac{3/5}{4/5} = \\frac{3}{4}$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 2,
    stem: "מהו ערכו של $\\sin 150°$?",
    choices: ["$\\frac{1}{2}$", "$-\\frac{1}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$-\\frac{\\sqrt{3}}{2}$"],
    correctIndex: 0,
    solutionSteps: [
      "$\\sin(180° - \\alpha) = \\sin \\alpha$",
      "$\\sin 150° = \\sin 30° = \\frac{1}{2}$",
    ],
    hint: "השתמש בזהות $\\sin(180° - \\alpha) = \\sin \\alpha$.",
    explanation: "$\\sin 150° = \\sin 30° = \\frac{1}{2}$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 2,
    stem: "מהו ערכו של $\\cos 120°$?",
    choices: ["$-\\frac{1}{2}$", "$\\frac{1}{2}$", "$-\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{3}}{2}$"],
    correctIndex: 0,
    solutionSteps: [
      "$\\cos(180° - \\alpha) = -\\cos \\alpha$",
      "$\\cos 120° = -\\cos 60° = -\\frac{1}{2}$",
    ],
    hint: "ברביע השני הקוסינוס שלילי.",
    explanation: "$\\cos 120° = -\\cos 60° = -\\frac{1}{2}$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 2,
    stem: "במשולש ישר זווית, הניצב מול הזווית $\\alpha$ הוא 6 והיתר הוא 10. מהו $\\sin \\alpha$?",
    choices: ["$\\frac{3}{5}$", "$\\frac{4}{5}$", "$\\frac{3}{4}$", "$\\frac{5}{3}$"],
    correctIndex: 0,
    solutionSteps: [
      "$\\sin \\alpha = \\frac{הניצב שמול הזווית}{היתר}$",
      "$\\sin \\alpha = \\frac{6}{10} = \\frac{3}{5}$",
    ],
    hint: "סינוס = הניצב שמול הזווית חלקי היתר.",
    explanation: "$\\sin \\alpha = \\frac{6}{10} = \\frac{3}{5}$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 2,
    stem: "פתור את המשוואה $\\cos x = 0$ בתחום $0 \\le x \\le 2\\pi$.",
    choices: [
      "$x = \\frac{\\pi}{2},\\ \\frac{3\\pi}{2}$",
      "$x = 0,\\ \\pi$",
      "$x = \\frac{\\pi}{2}$ בלבד",
      "$x = 0,\\ 2\\pi$",
    ],
    correctIndex: 0,
    solutionSteps: [
      "הקוסינוס מתאפס כאשר $x = \\frac{\\pi}{2} + \\pi k$",
      "בתחום הנתון: $x = \\frac{\\pi}{2}$ ו-$x = \\frac{3\\pi}{2}$",
    ],
    hint: "היכן גרף הקוסינוס חותך את ציר ה-$x$?",
    explanation: "בתחום $[0, 2\\pi]$ הקוסינוס מתאפס פעמיים: $\\frac{\\pi}{2}$ ו-$\\frac{3\\pi}{2}$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 3,
    stem: "פתור את המשוואה $\\sin x = \\frac{1}{2}$ בתחום $0 \\le x \\le 2\\pi$.",
    choices: [
      "$x = \\frac{\\pi}{6},\\ \\frac{5\\pi}{6}$",
      "$x = \\frac{\\pi}{6}$ בלבד",
      "$x = \\frac{\\pi}{3},\\ \\frac{2\\pi}{3}$",
      "$x = \\frac{\\pi}{6},\\ \\frac{7\\pi}{6}$",
    ],
    correctIndex: 0,
    solutionSteps: [
      "הפתרון הבסיסי: $x = \\frac{\\pi}{6}$",
      "הפתרון השני ברביע השני: $x = \\pi - \\frac{\\pi}{6} = \\frac{5\\pi}{6}$",
    ],
    hint: "לסינוס חיובי יש שני פתרונות: ברביע הראשון וברביע השני.",
    explanation: "$x = \\frac{\\pi}{6}$ וגם $x = \\frac{5\\pi}{6}$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 3,
    stem: "פתור את המשוואה $2\\cos x = \\sqrt{3}$ בתחום $0 \\le x \\le 2\\pi$.",
    choices: [
      "$x = \\frac{\\pi}{6},\\ \\frac{11\\pi}{6}$",
      "$x = \\frac{\\pi}{6},\\ \\frac{5\\pi}{6}$",
      "$x = \\frac{\\pi}{3},\\ \\frac{5\\pi}{3}$",
      "$x = \\frac{\\pi}{6}$ בלבד",
    ],
    correctIndex: 0,
    solutionSteps: [
      "$\\cos x = \\frac{\\sqrt{3}}{2}$",
      "הפתרון הבסיסי: $x = \\frac{\\pi}{6}$",
      "הפתרון השני: $x = 2\\pi - \\frac{\\pi}{6} = \\frac{11\\pi}{6}$",
    ],
    hint: "לקוסינוס חיובי יש פתרונות ברביע הראשון וברביע הרביעי.",
    explanation: "$\\cos x = \\frac{\\sqrt{3}}{2}$ נותן $x = \\frac{\\pi}{6}$ ו-$x = \\frac{11\\pi}{6}$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 3,
    stem: "כמה פתרונות יש למשוואה $\\sin(2x) = 0$ בתחום $0 \\le x \\le \\pi$?",
    choices: ["3", "2", "4", "1"],
    correctIndex: 0,
    solutionSteps: [
      "$\\sin(2x) = 0$ כאשר $2x = 0, \\pi, 2\\pi$",
      "כלומר $x = 0, \\frac{\\pi}{2}, \\pi$",
      "בסך הכול 3 פתרונות",
    ],
    hint: "כאשר $x$ בתחום $[0, \\pi]$, הביטוי $2x$ נמצא בתחום $[0, 2\\pi]$.",
    explanation: "$2x \\in \\{0, \\pi, 2\\pi\\}$ נותן $x = 0, \\frac{\\pi}{2}, \\pi$ — שלושה פתרונות.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 3,
    stem: "נתון: $\\sin x \\cos x = 0.3$. מהו $\\sin(2x)$?",
    choices: ["0.6", "0.3", "0.09", "0.15"],
    correctIndex: 0,
    solutionSteps: [
      "הזהות: $\\sin(2x) = 2\\sin x \\cos x$",
      "$\\sin(2x) = 2 \\cdot 0.3 = 0.6$",
    ],
    hint: "השתמש בזהות הזווית הכפולה: $\\sin(2x) = 2\\sin x\\cos x$.",
    explanation: "$\\sin(2x) = 2 \\cdot 0.3 = 0.6$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 3,
    stem: "מהי הנגזרת של הפונקציה $f(x) = \\sin(2x)$?",
    choices: ["$2\\cos(2x)$", "$\\cos(2x)$", "$-2\\cos(2x)$", "$2\\sin(2x)$"],
    correctIndex: 0,
    solutionSteps: [
      "כלל השרשרת: $(\\sin u)' = \\cos u \\cdot u'$",
      "$f'(x) = \\cos(2x) \\cdot 2 = 2\\cos(2x)$",
    ],
    hint: "אל תשכח להכפיל בנגזרת הפנימית לפי כלל השרשרת.",
    explanation: "לפי כלל השרשרת: $f'(x) = 2\\cos(2x)$.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 3,
    stem: "מהי נקודת המקסימום של הפונקציה $f(x) = \\sin x$ בתחום $0 \\le x \\le 2\\pi$?",
    choices: [
      "$\\left(\\frac{\\pi}{2},\\ 1\\right)$",
      "$\\left(\\pi,\\ 1\\right)$",
      "$\\left(\\frac{3\\pi}{2},\\ 1\\right)$",
      "$\\left(\\frac{\\pi}{2},\\ 0\\right)$",
    ],
    correctIndex: 0,
    solutionSteps: [
      "$f'(x) = \\cos x = 0 \\Rightarrow x = \\frac{\\pi}{2}, \\frac{3\\pi}{2}$",
      "$f\\left(\\frac{\\pi}{2}\\right) = 1$ — מקסימום; $f\\left(\\frac{3\\pi}{2}\\right) = -1$ — מינימום",
    ],
    hint: "גזור, השווה לאפס ובדוק את ערכי הפונקציה בנקודות החשודות.",
    explanation: "המקסימום מתקבל ב-$x = \\frac{\\pi}{2}$ עם ערך 1.",
  },
  {
    topicHe: "פונקציות טריגונומטריות",
    difficulty: 4,
    stem: "נתונה הפונקציה $f(x) = x + \\cos x$ בתחום $0 \\le x \\le 2\\pi$. באיזו נקודה $f'(x) = 0$?",
    choices: [
      "$x = \\frac{\\pi}{2}$",
      "$x = \\pi$",
      "$x = \\frac{3\\pi}{2}$",
      "$x = 0$",
    ],
    correctIndex: 0,
    solutionSteps: [
      "$f'(x) = 1 - \\sin x$",
      "$1 - \\sin x = 0 \\Rightarrow \\sin x = 1$",
      "בתחום הנתון: $x = \\frac{\\pi}{2}$",
    ],
    hint: "גזור והשווה לאפס: מתי $\\sin x = 1$?",
    explanation: "$f'(x) = 1 - \\sin x = 0$ מתקיים רק כאשר $\\sin x = 1$, כלומר $x = \\frac{\\pi}{2}$.",
  },
];

export const RATIONAL_QUESTIONS: SimpleQuestionSeed[] = [
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 1,
    stem: "מהו תחום ההגדרה של הפונקציה $f(x) = \\frac{1}{x-2}$?",
    choices: ["$x \\ne 2$", "$x \\ne 0$", "$x \\ne -2$", "כל $x$"],
    correctIndex: 0,
    solutionSteps: [
      "המכנה חייב להיות שונה מאפס",
      "$x - 2 \\ne 0 \\Rightarrow x \\ne 2$",
    ],
    hint: "מתי המכנה מתאפס?",
    explanation: "המכנה מתאפס ב-$x = 2$, ולכן תחום ההגדרה הוא $x \\ne 2$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 1,
    stem: "מהי האסימפטוטה האנכית של הפונקציה $f(x) = \\frac{3x}{x+5}$?",
    choices: ["$x = -5$", "$x = 5$", "$x = 3$", "$x = 0$"],
    correctIndex: 0,
    solutionSteps: [
      "אסימפטוטה אנכית מתקבלת כאשר המכנה מתאפס (והמונה לא)",
      "$x + 5 = 0 \\Rightarrow x = -5$",
    ],
    hint: "אסימפטוטה אנכית נמצאת בנקודה שבה המכנה מתאפס.",
    explanation: "המכנה מתאפס ב-$x = -5$, וזו האסימפטוטה האנכית.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 1,
    stem: "נתונה הפונקציה $f(x) = \\frac{x+3}{x-1}$. חשב את $f(3)$.",
    choices: ["3", "2", "6", "1.5"],
    correctIndex: 0,
    solutionSteps: [
      "$f(3) = \\frac{3+3}{3-1} = \\frac{6}{2}$",
      "$f(3) = 3$",
    ],
    hint: "הצב $x = 3$ בפונקציה.",
    explanation: "$f(3) = \\frac{6}{2} = 3$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 1,
    stem: "מהי נקודת החיתוך של הפונקציה $f(x) = \\frac{x-1}{x+2}$ עם ציר ה-$y$?",
    choices: [
      "$\\left(0,\\ -\\frac{1}{2}\\right)$",
      "$\\left(0,\\ \\frac{1}{2}\\right)$",
      "$(1,\\ 0)$",
      "$\\left(0,\\ -2\\right)$",
    ],
    correctIndex: 0,
    solutionSteps: [
      "חיתוך עם ציר $y$: מציבים $x = 0$",
      "$f(0) = \\frac{-1}{2} = -\\frac{1}{2}$",
    ],
    hint: "הצב $x = 0$.",
    explanation: "$f(0) = -\\frac{1}{2}$, ולכן נקודת החיתוך היא $\\left(0, -\\frac{1}{2}\\right)$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 2,
    stem: "מהי האסימפטוטה האופקית של הפונקציה $f(x) = \\frac{2x+1}{x-3}$?",
    choices: ["$y = 2$", "$y = 0$", "$y = 3$", "$y = -\\frac{1}{3}$"],
    correctIndex: 0,
    solutionSteps: [
      "דרגת המונה שווה לדרגת המכנה",
      "האסימפטוטה האופקית היא מנת המקדמים המובילים: $y = \\frac{2}{1} = 2$",
    ],
    hint: "כשדרגות המונה והמכנה שוות, חלק את המקדמים המובילים.",
    explanation: "$y = \\frac{2}{1} = 2$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 2,
    stem: "מהי האסימפטוטה האופקית של הפונקציה $f(x) = \\frac{x+1}{x^2+3}$?",
    choices: ["$y = 0$", "$y = 1$", "אין אסימפטוטה אופקית", "$y = \\frac{1}{3}$"],
    correctIndex: 0,
    solutionSteps: [
      "דרגת המכנה (2) גדולה מדרגת המונה (1)",
      "לכן האסימפטוטה האופקית היא $y = 0$",
    ],
    hint: "השווה בין דרגת המונה לדרגת המכנה.",
    explanation: "כשדרגת המכנה גדולה יותר, הפונקציה שואפת ל-0, כלומר $y = 0$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 2,
    stem: "מהו תחום ההגדרה של הפונקציה $f(x) = \\frac{x+1}{x^2-9}$?",
    choices: ["$x \\ne 3,\\ x \\ne -3$", "$x \\ne 3$", "$x \\ne 9$", "$x \\ne -1$"],
    correctIndex: 0,
    solutionSteps: [
      "$x^2 - 9 = 0 \\Rightarrow x^2 = 9$",
      "$x = 3$ או $x = -3$",
      "תחום ההגדרה: $x \\ne \\pm 3$",
    ],
    hint: "פרק את המכנה: $x^2 - 9 = (x-3)(x+3)$.",
    explanation: "המכנה מתאפס ב-$x = \\pm 3$, ולכן שני הערכים מחוץ לתחום ההגדרה.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 2,
    stem: "מהו תחום ההגדרה של הפונקציה $f(x) = \\frac{x}{x^2+1}$?",
    choices: ["כל $x$", "$x \\ne \\pm 1$", "$x \\ne 0$", "$x \\ne -1$"],
    correctIndex: 0,
    solutionSteps: [
      "$x^2 + 1 > 0$ לכל $x$ (ריבוע ועוד 1 תמיד חיובי)",
      "המכנה לעולם אינו מתאפס, ולכן תחום ההגדרה הוא כל $x$",
    ],
    hint: "האם $x^2 + 1$ יכול להתאפס?",
    explanation: "$x^2 + 1 \\ge 1$ לכל $x$, ולכן הפונקציה מוגדרת לכל $x$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 2,
    stem: "מהי הנגזרת של הפונקציה $f(x) = \\frac{1}{x}$?",
    choices: ["$-\\frac{1}{x^2}$", "$\\frac{1}{x^2}$", "$\\ln x$", "$-\\frac{1}{x}$"],
    correctIndex: 0,
    solutionSteps: [
      "$f(x) = x^{-1}$",
      "$f'(x) = -1 \\cdot x^{-2} = -\\frac{1}{x^2}$",
    ],
    hint: "כתוב את הפונקציה כחזקה: $x^{-1}$, וגזור לפי כלל החזקה.",
    explanation: "$\\left(x^{-1}\\right)' = -x^{-2} = -\\frac{1}{x^2}$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 2,
    stem: "פתור את המשוואה $\\frac{x+2}{x-1} = 2$.",
    choices: ["$x = 4$", "$x = 3$", "$x = 0$", "$x = -4$"],
    correctIndex: 0,
    solutionSteps: [
      "כופלים במכנה (בתנאי $x \\ne 1$): $x + 2 = 2(x-1)$",
      "$x + 2 = 2x - 2$",
      "$x = 4$ (מקיים $x \\ne 1$)",
    ],
    hint: "כפול את שני האגפים ב-$(x-1)$, וזכור לבדוק את תחום ההגדרה.",
    explanation: "$x + 2 = 2x - 2$ נותן $x = 4$, שנמצא בתחום ההגדרה.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 2,
    stem: "מהן האסימפטוטות של הפונקציה $f(x) = \\frac{1}{x^2}$?",
    choices: [
      "$x = 0$ ו-$y = 0$",
      "$x = 0$ בלבד",
      "$y = 0$ בלבד",
      "$x = 1$ ו-$y = 1$",
    ],
    correctIndex: 0,
    solutionSteps: [
      "המכנה מתאפס ב-$x = 0$ — אסימפטוטה אנכית",
      "כאשר $x \\to \\pm\\infty$ הפונקציה שואפת ל-0 — אסימפטוטה אופקית $y = 0$",
    ],
    hint: "בדוק גם את התאפסות המכנה וגם את ההתנהגות באינסוף.",
    explanation: "יש אסימפטוטה אנכית $x = 0$ ואסימפטוטה אופקית $y = 0$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 2,
    stem: "מהן נקודות החיתוך של הפונקציה $f(x) = \\frac{x^2-4}{x+1}$ עם ציר ה-$x$?",
    choices: [
      "$(2,\\ 0)$ ו-$(-2,\\ 0)$",
      "$(4,\\ 0)$ בלבד",
      "$(2,\\ 0)$ בלבד",
      "$(-1,\\ 0)$ ו-$(2,\\ 0)$",
    ],
    correctIndex: 0,
    solutionSteps: [
      "חיתוך עם ציר $x$: המונה מתאפס (והמכנה לא)",
      "$x^2 - 4 = 0 \\Rightarrow x = \\pm 2$",
      "שתי הנקודות בתחום ההגדרה ($x \\ne -1$)",
    ],
    hint: "פונקציה רציונלית מתאפסת כאשר המונה מתאפס.",
    explanation: "המונה מתאפס ב-$x = \\pm 2$, ושניהם בתחום ההגדרה.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 3,
    stem: "מהי האסימפטוטה האופקית של הפונקציה $f(x) = \\frac{3x^2+1}{x^2-4}$?",
    choices: ["$y = 3$", "$y = 0$", "$y = -\\frac{1}{4}$", "$y = 1$"],
    correctIndex: 0,
    solutionSteps: [
      "דרגת המונה שווה לדרגת המכנה (שתיהן 2)",
      "$y = \\frac{3}{1} = 3$",
    ],
    hint: "חלק את המקדמים המובילים של המונה והמכנה.",
    explanation: "$y = 3$ — מנת המקדמים המובילים.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 3,
    stem: "פתור את המשוואה $\\frac{x^2-9}{x-3} = 0$.",
    choices: ["$x = -3$ בלבד", "$x = 3$ בלבד", "$x = \\pm 3$", "אין פתרון"],
    correctIndex: 0,
    solutionSteps: [
      "המונה מתאפס כאשר $x = \\pm 3$",
      "אבל $x = 3$ מאפס גם את המכנה — מחוץ לתחום ההגדרה",
      "הפתרון היחיד: $x = -3$",
    ],
    hint: "בדוק אילו מהשורשים של המונה נמצאים בתחום ההגדרה.",
    explanation: "$x = 3$ נפסל כי הוא מאפס את המכנה, ולכן נותר רק $x = -3$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 3,
    stem: "מהו שיפוע המשיק לגרף הפונקציה $f(x) = \\frac{4}{x}$ בנקודה שבה $x = 2$?",
    choices: ["$-1$", "$1$", "$-2$", "$2$"],
    correctIndex: 0,
    solutionSteps: [
      "$f'(x) = -\\frac{4}{x^2}$",
      "$f'(2) = -\\frac{4}{4} = -1$",
    ],
    hint: "גזור את הפונקציה והצב $x = 2$.",
    explanation: "$f'(2) = -\\frac{4}{4} = -1$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 3,
    stem: "מה נכון לומר על הפונקציה $f(x) = \\frac{1}{x}$?",
    choices: [
      "יורדת בכל תחום הגדרתה",
      "עולה בכל תחום הגדרתה",
      "יורדת עבור $x < 0$ ועולה עבור $x > 0$",
      "יש לה נקודת קיצון",
    ],
    correctIndex: 0,
    solutionSteps: [
      "$f'(x) = -\\frac{1}{x^2}$",
      "$f'(x) < 0$ לכל $x \\ne 0$",
      "לכן הפונקציה יורדת בכל תחום הגדרתה",
    ],
    hint: "מהו סימן הנגזרת $-\\frac{1}{x^2}$?",
    explanation: "הנגזרת שלילית לכל $x \\ne 0$, ולכן הפונקציה יורדת בכל תחום הגדרתה.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 4,
    stem: "נתונה הפונקציה $f(x) = \\frac{x^2}{x-1}$. באילו ערכי $x$ יש לפונקציה נקודות קיצון?",
    choices: [
      "$x = 0$ ו-$x = 2$",
      "$x = 1$ בלבד",
      "$x = 0$ בלבד",
      "$x = -2$ ו-$x = 0$",
    ],
    correctIndex: 0,
    solutionSteps: [
      "כלל המנה: $f'(x) = \\frac{2x(x-1) - x^2}{(x-1)^2}$",
      "$f'(x) = \\frac{x^2 - 2x}{(x-1)^2} = \\frac{x(x-2)}{(x-1)^2}$",
      "$f'(x) = 0 \\Rightarrow x = 0$ או $x = 2$",
    ],
    hint: "גזור לפי כלל המנה והשווה את המונה לאפס.",
    explanation: "המונה של הנגזרת הוא $x(x-2)$, המתאפס ב-$x = 0$ ו-$x = 2$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 4,
    stem: "מהו הערך המקסימלי של הפונקציה $f(x) = \\frac{2x}{x^2+1}$?",
    choices: ["1", "2", "$\\frac{1}{2}$", "אין מקסימום"],
    correctIndex: 0,
    solutionSteps: [
      "$f'(x) = \\frac{2(x^2+1) - 2x \\cdot 2x}{(x^2+1)^2} = \\frac{2 - 2x^2}{(x^2+1)^2}$",
      "$f'(x) = 0 \\Rightarrow x^2 = 1 \\Rightarrow x = \\pm 1$",
      "$f(1) = \\frac{2}{2} = 1$ — מקסימום; $f(-1) = -1$ — מינימום",
    ],
    hint: "גזור לפי כלל המנה ובדוק את ערכי הפונקציה בנקודות הקיצון.",
    explanation: "המקסימום מתקבל ב-$x = 1$ עם ערך $f(1) = 1$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 4,
    stem: "מהי נקודת המינימום של הפונקציה $f(x) = \\frac{x^2+4}{x}$ בתחום $x > 0$?",
    choices: ["$(2,\\ 4)$", "$(4,\\ 5)$", "$(1,\\ 5)$", "$(-2,\\ -4)$"],
    correctIndex: 0,
    solutionSteps: [
      "$f(x) = x + \\frac{4}{x}$, ולכן $f'(x) = 1 - \\frac{4}{x^2}$",
      "$f'(x) = 0 \\Rightarrow x^2 = 4 \\Rightarrow x = 2$ (בתחום $x > 0$)",
      "$f(2) = 2 + 2 = 4$ — נקודת מינימום $(2, 4)$",
    ],
    hint: "פשט את הפונקציה ל-$x + \\frac{4}{x}$ לפני הגזירה.",
    explanation: "הנגזרת מתאפסת ב-$x = 2$, ושם $f(2) = 4$.",
  },
  {
    topicHe: "פונקציות רציונליות",
    difficulty: 4,
    stem: "עבור אילו ערכי $x$ הפונקציה $f(x) = \\frac{2x-6}{x+1}$ חיובית?",
    choices: [
      "$x < -1$ או $x > 3$",
      "$-1 < x < 3$",
      "$x > 3$ בלבד",
      "$x > -1$ בלבד",
    ],
    correctIndex: 0,
    solutionSteps: [
      "המונה מתאפס ב-$x = 3$, המכנה ב-$x = -1$",
      "בודקים סימנים בכל תחום: עבור $x < -1$ שניהם שליליים — מנה חיובית",
      "עבור $-1 < x < 3$: מונה שלילי, מכנה חיובי — מנה שלילית",
      "עבור $x > 3$: שניהם חיוביים — מנה חיובית",
    ],
    hint: "מצא את נקודות האפס של המונה והמכנה ובדוק סימנים בכל קטע.",
    explanation: "המנה חיובית כאשר המונה והמכנה בעלי אותו סימן: $x < -1$ או $x > 3$.",
  },
];
