$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Force -Path "stitch_screens" | Out-Null

Write-Host "Downloading Screen 1..."
curl.exe -L "https://lh3.googleusercontent.com/aida/AP1WRLuLTeJ0EyWYEjVvUxaz97kosKPGZnhImetJ4gSbtrhWELZ5ycuK8kmTcm6SIxpdzGbSrbGWq9DZeoTrXAZ_8A-lGBCNgIFlRcoMTfEbu3DIYWUiIoS0hwsSTH1psIWcJnZKZi1-LF0ZLuNk4mEC212tn9mDrgTvyCoHvjV-ayhLNKsitWBRyrGTGQ4-BPpYSDS-yxontcTvRB9eUysOSwF1VsnANXuGiOWblBHm8jt4DSNyzuqF2jBPe3Q" -o "stitch_screens\1_Mode_Selection_Immersive_Dark.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2ZiOWZhNWU5YTRhYzQ1ZmJiYWIyNmE4ODlhZWI4NDkxEgsSBxDwyNG9hRsYAZIBIwoKcHJvamVjdF9pZBIVQhMxOTk3ODAwNDczNzcxODU5MTU4&filename=&opi=89354086" -o "stitch_screens\1_Mode_Selection_Immersive_Dark.html"

Write-Host "Downloading Screen 2..."
curl.exe -L "https://lh3.googleusercontent.com/aida/AP1WRLvIlH6A3fRNHKOgP86pFRyB-U3WDx_MoWC9Ip_WX-95ULdCfrcrk6kUaH9T_zUEabJvpUfn2s_pH1pQ2WP4eOpzmHiQmZLgPThX-qmWsa_fgS8zv26FRxzqSSHu7vrSZke7ZDmrloNbqhGzPhAG0NYlSZ__634gHF4mVxB3fP9iwc_LOHLz1DUeG5mlf897JXott4egWqUMxV-GQJyXBydqQM0ssYHiAg2AArcnUKzMjBiREjw" -o "stitch_screens\2_Assigned_Tasks_Immersive_Dark.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2VmN2EwZDljMWQwNDRhOTI4ZjBlODY5M2ZmMjA2ODVlEgsSBxDwyNG9hRsYAZIBIwoKcHJvamVjdF9pZBIVQhMxOTk3ODAwNDczNzcxODU5MTU4&filename=&opi=89354086" -o "stitch_screens\2_Assigned_Tasks_Immersive_Dark.html"

Write-Host "Downloading Screen 3..."
curl.exe -L "https://lh3.googleusercontent.com/aida/AP1WRLsfrYGj3HMaxye0zw3doqDN_3PqNw-hXIB8LHJaauyO1yVd6GdwrP_uBhs5T_c5P0vy6Is1DAdctks-vyjy-15bP6OZpt5OQ7n1tqQ9sP_xW9Lo0brneefkkWmprloEgNk4j6sbLluiv4PDc96YuR4wISjUE4IOWafs0Q1bknVKuharSbI0Bba_tMPmFfmX3DEXYPzee6ujuZVZheR639Vgts0XHsEGk3XiTjAywVFg4lSdA1eEOfJbUO4" -o "stitch_screens\3_Assigned_Tasks_Academic_Light.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzFhMzFhMjczMzZjZDQ0OGRhMmY3MzBiZmZlOWQxMDk0EgsSBxDwyNG9hRsYAZIBIwoKcHJvamVjdF9pZBIVQhMxOTk3ODAwNDczNzcxODU5MTU4&filename=&opi=89354086" -o "stitch_screens\3_Assigned_Tasks_Academic_Light.html"

Write-Host "Downloading Screen 4..."
curl.exe -L "https://lh3.googleusercontent.com/aida/AP1WRLtkz3gPWtWAWmVQ-N25dW25_KHQmfM_jMAIGhq1yhWdH_jb4kC7VQlurQ4a0sRtUwN2Sq8KOMUzxNZ4aR3iu9BFe_7iG10UK1d9GwFu9af6qpXcpKlBJOJIMPDwkbwvQN_QuQpNflROO6ptQIul--b7SQ8lrAjDrpI6VeSP0lfXJUqnK_8X3UPXmfl5Pahi0-lxHVbZf2IJiJF0H3jetRhRn_GbsMOiptaoOHDNYEkNEruINu5_qY9ex7U" -o "stitch_screens\4_Learning_Progress_Academic_Light.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzE4MmEzYTliMjg5NTRlZDhhZDQxYWFjNThkNTg5N2E2EgsSBxDwyNG9hRsYAZIBIwoKcHJvamVjdF9pZBIVQhMxOTk3ODAwNDczNzcxODU5MTU4&filename=&opi=89354086" -o "stitch_screens\4_Learning_Progress_Academic_Light.html"

Write-Host "Downloading Screen 5..."
curl.exe -L "https://lh3.googleusercontent.com/aida/AP1WRLtba0ecHE4Ql0h6km8YrtxUX7jTwHYTf3ty6N371NrMCMOvI9kyoVLO4XTwnuQWJV7m5Dec9C2h5_IpTafsyCL9FdCw_V22ZLYo3LPfGZpffCnIZbPIPtQsvL1hl5lHEfb-Xmq4lVj2U8wSbJY-fWlzMboqKGjyodFL12LoRqa0UZ57nF3bxQQUm9v1edIp4BJ_310SD-dSrmTLvBY4YxnMEIXBlXJvP-HXcBtDJe_t54e7gSmPWoP_5jk" -o "stitch_screens\5_Learning_Progress_Immersive_Dark.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzJkMzI5NDI0ZDY4ZDQ3YWM4YWNlM2Y4YjVhMWU5M2FmEgsSBxDwyNG9hRsYAZIBIwoKcHJvamVjdF9pZBIVQhMxOTk3ODAwNDczNzcxODU5MTU4&filename=&opi=89354086" -o "stitch_screens\5_Learning_Progress_Immersive_Dark.html"

Write-Host "Downloading Screen 6..."
curl.exe -L "https://lh3.googleusercontent.com/aida/AP1WRLvVyItQQVampSP9o1wnxyrk1oN_yzwghsJfXhS8RBIm8MpLUZer6r0nX1n4xtBgfqd3xumLxdoWHqNzvotoSEwVfDRW6c7ELPyQOvfV-BPnLBhKjX9Qtn9prLa1Z84sKaQY6Ib-wDJBnu85DgnrOPG2eJJeF7VjSdpE7RTz2bSll0Sg5ZTsS2mTnVFT3m93VgPYdnDG5UBjw_DUkeSOR9hUkhL2Q4qj464IgDjyrSP_PRehblONEhMbow" -o "stitch_screens\6_Mode_Selection_Academic_Light.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2Q2MGQzOGQ1MWQ4ZjRjMDg4MzZhOWU5ZDFmYjE3YjE5EgsSBxDwyNG9hRsYAZIBIwoKcHJvamVjdF9pZBIVQhMxOTk3ODAwNDczNzcxODU5MTU4&filename=&opi=89354086" -o "stitch_screens\6_Mode_Selection_Academic_Light.html"

Write-Host "Downloading Screen 7..."
curl.exe -L "https://lh3.googleusercontent.com/aida/AP1WRLuQXeLW07I9IcXP28RuT0N40pkF3nNH6GT_5QuJ0CcKkz7RUPOco-S63dYJMhX0zgkAgT4AqXP2nlxvYC5jWRo4bJPx4kNdC-vodp4OhL2bzWy9CRWv8962-It7q1M2YzKkZvMI5aYoZ5KQEGBJ0aP3s1eSrvm5ePk0Jn72Duu6t7MfAlKHlYwrMDj2KEVLZI1Bm6ajKxR4QtfopyW69xLOYcT5AiMN07qNNLrxzwvkYilL1dy9VdidGq4" -o "stitch_screens\7_AI_Terminal_Immersive_Dark.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzczZDBlYTk1OTBhNTQxYjI5OGNlNmVkN2IwYWI5NzA0EgsSBxDwyNG9hRsYAZIBIwoKcHJvamVjdF9pZBIVQhMxOTk3ODAwNDczNzcxODU5MTU4&filename=&opi=89354086" -o "stitch_screens\7_AI_Terminal_Immersive_Dark.html"

Write-Host "Downloading Screen 8..."
curl.exe -L "https://lh3.googleusercontent.com/aida/AP1WRLtsNicHFAtT08EFq3WGFlF-7OeOV56sEjnCIlp6F8ogbjxb6oZlkQOMV8q91HCjEmCKgf9Hxcbh0Q7g8YMh8pOIffaqOzpLIEU0qvLfMjShVrJ7qDXOOIC_zqvDJq9ie2mBDaHH1pvVwDaLyP2LowCEtc4inSbEn7nUk4tDMDY8hGSd7DRFubUGvk3OmUNLZrgpCBeE4J0joEIflczvOn6CWybWKZvBqA8TkX2OLayEe_LD0bNQJmFUZtY" -o "stitch_screens\8_AI_Terminal_Academic_Light.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2UxYTljZWNhZTQ0MDQyNjBiZTExMmZkNjcwZDZiMWE2EgsSBxDwyNG9hRsYAZIBIwoKcHJvamVjdF9pZBIVQhMxOTk3ODAwNDczNzcxODU5MTU4&filename=&opi=89354086" -o "stitch_screens\8_AI_Terminal_Academic_Light.html"

Write-Host "Downloading Screen 9..."
curl.exe -L "https://lh3.googleusercontent.com/aida/AP1WRLvZdAqPQWJL896Uz290zyqrupamJKbhBP0ljcicGadDJjorBwz3Ydpd2gRRk2G-MZmvU30ZsQ_ccr6iFyIlJq1v8on-uqa5rmsf6But1E-o_NxHBBw9OTu0oDYICC5WIslXSlBtsJRDKIAHUY9fNvtijt0yZ3jk7optnXXJyuwa5_401_PO_qjdHOG5frWaoL3G6wUeIs1IdMlfIhjhdFjeDgceLiGn_Q6DHmgB4YIWM2kgCvkUx5mgQA" -o "stitch_screens\9_Student_Map_Modern_Academic_Revamped.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzE1YmJhMGUxOTMwMDQ2ZjliMzM0NTgwNTVhNWQ1OGFiEgsSBxDwyNG9hRsYAZIBIwoKcHJvamVjdF9pZBIVQhMxOTk3ODAwNDczNzcxODU5MTU4&filename=&opi=89354086" -o "stitch_screens\9_Student_Map_Modern_Academic_Revamped.html"

Write-Host "Done!"
