/**
 * The one framing box every piece of mascot art goes through, and the keying
 * that gets it there. Shared by slice-poses.mjs, cut-rig-layers.mjs and
 * cut-gestures.mjs, which had three copies of this between them.
 *
 * ## Why one box matters
 *
 * Everything downstream assumes his head is the same size in the same place in
 * every asset. The rig's hands are cut from one pose and worn by a head cut from
 * another; the flat pose PNG stands in as a placeholder while the rig's twelve
 * layers load, and any mismatch shows up as a jump the moment it swaps.
 *
 * Two bugs came from getting this wrong. Letting an arm pose grow its own box
 * shipped `happy` 8.3% smaller than `idle`. Letting the rig frame on its own
 * bounds made it 13% bigger than the pose PNGs, which is exactly the placeholder
 * jump. Both are the same mistake: framing derived per-asset instead of once.
 *
 * The centre comes from the idle portrait, which is the reference pose. The side
 * is whatever the most sprawling pose needs about that centre, so raised arms
 * fit without anything being scaled to make room.
 */
import { readFileSync } from "node:fs";
import { decodePng, resample } from "./png.mjs";

export const IDLE_SOURCE = "assets-src/faraday-hires.png";
/** Poses with hands. Their extents decide how wide the shared box has to be. */
export const POSE_SOURCES = ["thinking", "happy", "wrong", "streak", "blink"]
  .map((name) => ({ name, file: `assets-src/poses/${name}.png` }));

/**
 * Magenta by the relationship between channels, not by equality — the model
 * never returns exactly #FF00FF, and this art came back 224,27,200. Magenta is
 * the one hue absent from his palette, so his skin, white hair and dark
 * outlines all fail this test and survive the key.
 */
export const isBg = (r, g, b) => Math.min(r, b) - g > 30;

/**
 * Punch out the backdrop by flooding inward from the border, so a magenta-ish
 * pixel *inside* the drawing survives — a colour key would put holes in him.
 * Then despill: the key leaves a magenta cast on anti-aliased edge pixels, and
 * without pulling green back up he ships with a purple fringe.
 */
export function key(px, w, h) {
  const seen = new Uint8Array(w * h), stack = [];
  for (let x = 0; x < w; x++) stack.push(x, (h - 1) * w + x);
  for (let y = 0; y < h; y++) stack.push(y * w, y * w + w - 1);
  while (stack.length) {
    const p = stack.pop();
    if (seen[p]) continue;
    seen[p] = 1;
    const i = p * 4;
    if (!isBg(px[i], px[i + 1], px[i + 2])) continue;
    px[i + 3] = 0;
    const x = p % w, y = (p - x) / w;
    if (x > 0) stack.push(p - 1);
    if (x < w - 1) stack.push(p + 1);
    if (y > 0) stack.push(p - w);
    if (y < h - 1) stack.push(p + w);
  }
  for (let p = 0; p < w * h; p++) {
    const i = p * 4;
    if (px[i + 3] < 32) continue;
    const lo = Math.min(px[i], px[i + 2]);
    if (lo - px[i + 1] > 20) px[i + 1] = lo;
  }
}

/** Tight bounds of whatever survived the key. */
export function bounds(px, w, h) {
  let x0 = w, x1 = 0, y0 = h, y1 = 0;
  for (let p = 0; p < w * h; p++) {
    if (px[p * 4 + 3] <= 24) continue;
    const x = p % w, y = (p - x) / w;
    if (x < x0) x0 = x;
    if (x > x1) x1 = x;
    if (y < y0) y0 = y;
    if (y > y1) y1 = y;
  }
  return { x0, x1, y0, y1, w: x1 - x0 + 1, h: y1 - y0 + 1 };
}

/** Decode a source, key it, and measure it. */
export function keyed(file) {
  const img = decodePng(readFileSync(file));
  const px = new Uint8ClampedArray(img.px);
  key(px, img.w, img.h);
  return { px, w: img.w, h: img.h, b: bounds(px, img.w, img.h) };
}

/**
 * The shared box: centred on idle, sized to hold every pose that exists.
 *
 * Missing pose files are skipped rather than throwing, because they arrive one
 * at a time when they are generated by hand. That does mean the box can widen
 * as poses land — so re-run every cutter together, or the rig and the poses
 * drift apart again.
 */
export function sharedFrame(extraSources = []) {
  const idle = keyed(IDLE_SOURCE);
  const cx = idle.b.x0 + idle.b.w / 2;
  const cy = idle.b.y0 + idle.b.h / 2;
  const others = [...POSE_SOURCES, ...extraSources]
    .map(({ file }) => { try { return keyed(file); } catch { return null; } })
    .filter(Boolean);
  const side = Math.max(
    Math.max(idle.b.w, idle.b.h) * 1.1,
    ...[idle, ...others].map((k) => Math.max(
      2 * Math.abs(k.b.x0 + k.b.w / 2 - cx) + k.b.w,
      2 * Math.abs(k.b.y0 + k.b.h / 2 - cy) + k.b.h,
    ) * 1.06),
  );
  return { cx, cy, side, idle };
}

/** Resample a keyed source through the shared box at `size`. */
export function through({ cx, cy, side }, k, size) {
  return resample(k.px, k.w, k.h, cx - side / 2, cy - side / 2, side, size);
}
